name: Deploy to Azure App Service

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          cd api   # ya src (jaha package.json hai)
          npm install
          npm run build --if-present

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: i2k2-azuredashboard
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
